version: '2'

services:
  web:
    image: vulong/piccolo_web:1.0
    build: ./
    ports:
        - "13000:3000"
        - "13443:3443"
    networks:
        - piccolo
    restart: unless-stopped
networks:
    piccolo:
        external:
            name: piccolo_default
